# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: steph-variable-group

steps:
- task: CmdLine@2
  inputs:
    script: 'git pull https://github.com/Smarker/test-project.git master'

- task: CmdLine@2
  inputs:
    script: 'git push https://$(githubpersonaltoken)@github.com/Smarker/test-project.git HEAD:master'
