# Pull changes from github then push latest devops changes to github

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: steph-variable-group

steps:
- task: CmdLine@2
  inputs:
    script: 'git pull https://$(githubpersonaltoken)@github.com/Smarker/test-project.git master'

- task: CmdLine@2
  inputs:
    script: 'git push https://$(githubpersonaltoken)@github.com/Smarker/test-project.git HEAD:master'
